from pathlib import Path
import json
items=[]

def add(cat, rows):
    for en, te, unit, price in rows:
        items.append({'category':cat,'en':en,'te':te,'unit':unit,'price':price})

add('Traditional Sweets', [
('Bellam Sunnundalu','బెల్లం సున్నుండలు','1 Kg',640),('Ravva Laddu','రవ్వ లడ్డు','1 Kg',480),('Nuvvula Undalu','నువ్వులుండలు','1 Kg',400),('Kobbari Laddu','కొబ్బరి లడ్డు','1 Kg',500),('Dry Fruits Pootharekulu','డ్రై ఫ్రూట్స్ పూతరేకులు','5 Pcs',120),('Kobbari Kajjikayalu','కొబ్బరి కజ్జికాయలు','1 Kg',440),('Paakam Kajjikayalu','పాకం కజ్జికాయలు','1 Kg',440),('Palli Chekki','పల్లీ చెక్కి','1 Kg',320),('Nuvvula Chekki','నువ్వుల చెక్కి','1 Kg',320),('Seeds Nuts Chekki','నువ్వు – శనగ చెక్కి','1 Kg',600),('Bellam Gavvalu','బెల్లం గవ్వలు','1 Kg',360),('Bellam Kommulu','బెల్లం కొమ్ములు','1 Kg',320),('Gorimetailu','గోరిమెట్లలు','1 Kg',320),('Ariselu','అరిసెలు','1 Kg',400),('Pakundalu','పాకుండలు','1 Kg',320),('Chalimidi','చలిమిడి','1 Kg',360),('Ghulabi Puvvulu','గులాబీ పువ్వులు','1 Kg',320),('Dry Fruits Halwa','డ్రై ఫ్రూట్స్ పాకం','1 Kg',1000),('Goduma Halwa','గోధుమ హల్వా','1 Kg',600),('Carrot Halwa','క్యారెట్ హల్వా','1 Kg',800),('Badam Milk','బాదం పాలు','',50),('Ghee Bobbatlu','నెయ్యి బొబ్బట్లు','5 Pcs',None),('Bellam Junnu','బెల్లం జున్ను','1 Kg',500),('Ghee Laddu','నెయ్యి లడ్డు','1 Kg',800)])
add('Laddu & Special Sweets', [
('Thokudu Laddu','తొక్కుడు లడ్డు','1 Kg',400),('Boondi Laddu','బూందీ లడ్డు','1 Kg',320),('Motichoor Laddu','మోతిచూర్ లడ్డు','1 Kg',320),('Badusha','బాదుషా','1 Kg',320),('Mysore Pak','మైసూర్ పాక్','1 Kg',320),('Jangiri','జాంగిరి','1 Kg',320),('Nuvvula Palli Laddu','నువ్వుల పల్లి లడ్డు','1 Kg',400),('Chimili Laddu','చిమిలి లడ్డు','1 Kg',400),('Ravva Gajji Kayalu','రవ్వ గజ్జి కాయలు','5 Pcs',500),('Thati Garelu','తాటి గారెలు','1 Piece',15),('Kaju Chekki','కాజు చెక్కి','1 Kg',1200),('Boondi Chekki','బూందీ చెక్కి','1 Kg',300),('Thati Bellam Chimili','తాటి బెల్లం చిమిలి','1 Kg',600),('Black Sesame Laddu','నల్ల నువ్వుల లడ్డు','1 Kg',400),('Avisa Laddu','అవిస లడ్డు','1 Kg',400),('Dry Fruit Laddu','డ్రై ఫ్రూట్ లడ్డు','1 Kg',1200)])
add('Pickles', [
('Avakaya','ఆవకాయ','1 Kg',520),('Magaya','మాగాయ','1 Kg',520),('Lemon Pickle','నిమ్మకాయ పచ్చడి','1 Kg',520),('Vusiri Kaya','ఉసిరికాయ','1 Kg',520),('Vusiri Thoku','ఉసిరి తొక్కు','1 Kg',520),('Tomato Pickle','టమాటా పచ్చడి','1 Kg',500),('Pandu Mirchi','పండు మిరపకాయ','1 Kg',400),('Coriander Pickle','కొత్తిమీర పచ్చడి','1 Kg',600),('Gongura Pickle','గోంగూర పచ్చడి','1 Kg',600),('Ginger Pickle','అల్లం పచ్చడి','1 Kg',600),('Bellam Avakaya','బెల్లం ఆవకాయ','1 Kg',600),('Debbakaya Pickle','దెబ్బకాయ పచ్చడి','1 Kg',400)])
add('Karam Podi & Masalas', [
('Kandi Podi','కంది పొడి','1 Kg',400),('Dhaniyala Podi','ధనియాల పొడి','1 Kg',400),('Avasi','అవిసె పొడి','1 Kg',400),('Pasara','పసర పొడి','1 Kg',400),('Sesame Karam Podi','నువ్వుల కారం పొడి','1 Kg',400),('Sesame Verusanga Karam','నువ్వుల వేరుశనగ కారం పొడి','1 Kg',400),('Sondi Podi','సోంటి పొడి','1 Kg',800),('Pala Sondi','పాల సోంటి పొడి','1 Kg',800),('Curry Leaf','కరివేపాకు పొడి','1 Kg',800),('Munagaku Karam','మునగాకు కారం పొడి','1 Kg',800),('Nalla Karam','నల్ల కారం పొడి','1 Kg',600),('Velluli Karam','వెల్లుల్లి కారం పొడి','1 Kg',400),('Kakarikai Karam','కాకరకాయ కారం పొడి','1 Kg',400),('Gongura','గోంగూర పొడి','1 Kg',600),('Pudina','పుదీనా పొడి','1 Kg',600),('Kutimera','కొత్తిమీర పొడి','1 Kg',600),('Mirchi Karam','మిర్చి కారం పొడి','1 Kg',400),('Dry Fruit Karam','డ్రై ఫ్రూట్ కారం పొడి','1 Kg',1000),('Jira Powder','జీలకర్ర పొడి','1 Kg',500),('Chicken Masala','చికెన్ మసాలా పొడి','1 Kg',1000),('Mutton Masala','మటన్ మసాలా పొడి','1 Kg',1000),('Rasam Podi','రసం పొడి','1 Kg',600),('Sambar Podi','సాంబార్ పొడి','1 Kg',600),('Instant Chutney Powder','ఇన్‌స్టంట్ చట్నీ పొడి','1 Kg',600)])
add('Milk Sweets', [
('Milk Sweet','మిల్క్ స్వీట్','1 Piece',25),('Kaju Burfi','కాజు బర్ఫీ','1 Kg',1000),('Kaju Sompapidi','కాజు సోంపాపిడి','1 Kg',1200),('Ghee Mysore Pak','నెయ్యి మైసూర్ పాక్','1 Kg',800),('Milk Mysore Pak','మిల్క్ మైసూర్ పాక్','1 Kg',600),('Gulab Jamun','గులాబ్ జామ్','1 Kg',400),('Meethu Chaman Laddu','మీతూ చమన్ లడ్డు','1 Kg',320),('Pala Kova','పాల కోవా','1 Kg',840),('Kalakand','కలాకంద్','1 Kg',1000),('Rasugula','రసగుల్లా','1 Kg',320),('Badam Milk','బాదం మిల్క్','',55),('Kova Cashew Kajjikayalu','కోవా జీడి కజ్జికాయలు','1 Kg',400),('Paneer Jilabi','పనీర్ జిలేబి','1 Kg',400),('Dry Fruit Burfi','డ్రై ఫ్రూట్ బర్ఫీ','1 Kg',800)])
add('Hot Items & Snacks', [
('Jantikalu','జంతికలు','1 Kg',320),('Ragi Chekkalu','రాగి చెక్కలు','1 Kg',320),('Jonna Chekkalu','జొన్న చెక్కలు','1 Kg',320),('Varipindi Chekkalu','వరిపిండి చెక్కలు','1 Kg',320),('Saggubiyyam Chekkalu','సగ్గుబియ్యం చెక్కలు','1 Kg',320),('Masala Chekkalu','మసాలా చెక్కలు','1 Kg',320),('Chitti Appadalu','చిట్టి అప్పడాలు','1 Kg',320),('Chitti Chegodi','చిట్టి చేగోడీలు','1 Kg',320),('Pappu Chegodi','పప్పు చేగోడీలు','1 Kg',320),('Karapu Chegodi','కారపు చేగోడీలు','1 Kg',320),('Pudina Murukulu','పుదీనా మురుకులు','1 Kg',320),('Betroot Murukulu','బీట్‌రూట్ మురుకులు','1 Kg',320),('Murukulu Jantikalu','మురుకుల జంతికలు','1 Kg',320),('Karam Boondi','కారం బూంది','1 Kg',320),('Sanna Karamposa','సన్న కారప్పూస','1 Kg',320),('Pedha Karamposa','పెద్ద కారప్పూస','1 Kg',320),('Dry Fruits Mix','డ్రై ఫ్రూట్స్ మిక్స్','1 Kg',1200),('Kaju Karam','కాజు కారం','1 Kg',320),('Kaju Pakodi','కాజు పకోడి','1 Kg',1200),('Palli Pakodi','పల్లి పకోడి','1 Kg',400),('Kakarikai Pakodi','కాకరకాయ పకోడి','1 Kg',320),('Corn Flakes','కార్న్ ఫ్లేక్స్','1 Kg',280),('Atukulu Mixture','అటుకుల మిక్స్','1 Kg',280),('Dal Mixture','పప్పు మిక్స్','1 Kg',320),('Aku Pakodi','ఆకు పకోడి','1 Kg',320),('Karam Gavvalu','కారం గవ్వలు','1 Kg',320)])
assert len(items)==116, len(items)

root=Path('/mnt/data/sahasra-home-foods')
(root/'data.js').write_text('const MENU_ITEMS = '+json.dumps(items,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
